#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Sort-Naturally
Version  : 1.03
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Sort-Naturally-1.03.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Sort-Naturally-1.03.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libs/libsort-naturally-perl/libsort-naturally-perl_1.03-2.debian.tar.xz
Summary  : 'sort lexically, but sort numeral parts numerically'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Sort-Naturally-man

%description
Time-stamp: "2001-05-25 21:17:33 MDT"
Sort::Naturally
[extracted from the Pod...]

%package man
Summary: man components for the perl-Sort-Naturally package.
Group: Default

%description man
man components for the perl-Sort-Naturally package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Sort-Naturally-1.03
mkdir -p %{_topdir}/BUILD/Sort-Naturally-1.03/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Sort-Naturally-1.03/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Sort/Naturally.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Sort::Naturally.3
